ex_compile: ex_compile.c
	gcc -Wall -g -o ex_compile ex_compile.c $(shell pkg-config --cflags --libs glib-2.0)

word_count: word_count.c
	gcc -Wall -g -o word_count word_count.c $(shell pkg-config --cflags --libs glib-2.0)